### ISSUE TITLE
[BUG] some items in deviceProperties do not have value

### ISSUE THREAD

**Issue by wawlian** [openyurtio/yurt-device-controller#16]
**What happened**:
when checking status of device with `kubectl get device xxx -o yaml`, some of the items in status.deviceProperties do not have values while the response of EdgeX API contains value. Here is and example below:
![image](https://user-images.githubusercontent.com/1227737/148487956-c8f6ebb6-6430-49c0-bcaa-6f74cdc4bd1c.png)

![image](https://user-images.githubusercontent.com/1227737/148488058-63934b90-4f51-4eff-b188-0c1998c862ec.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Just create a device and check the status.

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:  v0.5.0
- Kubernetes version (use `kubectl version`): 1.18.8

**others**

/kind bug

**Comment by qclc** [comment]
Thanks for raising this bug. Are you willing to be responsible for fixing this bug? @wawlian
