### ISSUE TITLE
[feature request] Support Edgex Jakarta

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/yurt-device-controller#25]
**What would you like to be added**:

Support Edgex [Jakarta](https://wiki.edgexfoundry.org/display/FA/Jakarta) version, and is not backward compatible with Hanoi.

**Why is this needed**:

[Jakarta](https://wiki.edgexfoundry.org/display/FA/Jakarta) is first [LTS release](https://wiki.edgexfoundry.org/pages/viewpage.action?pageId=69173332).

**others**
/kind feature

**Comment by wawlian** [comment]
@huiwq1990 The OpenYurt community and the EdgeX community are working closely together to support this feature and it is expected to be released in OpenYurt v0.7.0.

**Comment by huiwq1990** [comment]
> @huiwq1990 The OpenYurt community and the EdgeX community are working closely together to support this feature and it is expected to be released in OpenYurt v0.7.0.

 When will OpenYurt v0.7.0 release?

**Comment by wawlian** [comment]
This feature is supported, the code is merged to release-0.2.0
